# Generated by Django 4.0.4 on 2022-04-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='event_covers')),
                ('has_happend', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
