# Generated by Django 4.0.4 on 2022-04-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.FloatField(default=50.0),
            preserve_default=False,
        ),
    ]
