# Generated by Django 4.0.4 on 2022-04-17 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventpictures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlideShow',
            new_name='Slide',
        ),
    ]
