# Generated by Django 4.0.4 on 2022-04-17 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_rename_slideshow_slide'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventPictures',
            new_name='EventPicture',
        ),
    ]
